services:
  - type: web
    name: task-manager-backend
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: glocation_prueba_bd
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001