static_sites:
  - name: task-manager-frontend
    buildCommand: npm install && npm run build
    publishDirectory: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://pruebaglocation.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html